### Broadcasting in Python

In [2]:
import numpy as np

In [3]:
arr  = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
sum = np.sum(arr, axis=0)
sum

array([12, 15, 18])

In [5]:
sum.shape

(3,)

In [6]:
result = (arr / sum)* 100
result

array([[ 8.33333333, 13.33333333, 16.66666667],
       [33.33333333, 33.33333333, 33.33333333],
       [58.33333333, 53.33333333, 50.        ]])

In [7]:
1 / (1+4+7)

0.08333333333333333

In [9]:
result = np.abs(arr) / np.abs(arr).max()
result

array([[0.11111111, 0.22222222, 0.33333333],
       [0.44444444, 0.55555556, 0.66666667],
       [0.77777778, 0.88888889, 1.        ]])